# Generated by Django 5.1.2 on 2024-10-18 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deductions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('received_money', models.IntegerField(default=-1)),
                ('give_money', models.IntegerField(default=-1)),
                ('deduct_per_payslip', models.IntegerField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code_name', models.CharField(max_length=10, unique=True)),
                ('found_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeductionEligibility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductionEligibility', to='employeeManagement_app.deductions')),
                ('employee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeManagement_app.employeetype')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDeductions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('remaining_money', models.IntegerField(default=-1)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('approved_date', models.DateField(blank=True, default=None, null=True)),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeManagement_app.deductions')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_num', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=200)),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(max_length=10)),
                ('joined_date', models.DateField()),
                ('photo_url', models.URLField(blank=True, default=None, null=True)),
                ('faculty', models.CharField(max_length=20)),
                ('allowed_leaves', models.SmallIntegerField(default=0)),
                ('main_payscale', models.IntegerField(default=0)),
                ('deductions', models.ManyToManyField(through='employeeManagement_app.EmployeeDeductions', to='employeeManagement_app.deductions')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employeeManagement_app.departments')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employeeManagement_app.employeetype')),
            ],
        ),
        migrations.AddField(
            model_name='employeedeductions',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeManagement_app.employees'),
        ),
        migrations.AddField(
            model_name='deductions',
            name='eligible_employee_type_ids',
            field=models.ManyToManyField(through='employeeManagement_app.DeductionEligibility', to='employeeManagement_app.employeetype'),
        ),
    ]
