# Generated by Django 5.1.2 on 2024-10-31 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compensations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('money_per_payslip', models.IntegerField(default=0)),
                ('desc', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deductions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('tax', 'Tax'), ('insurance', 'Insurance'), ('loan', 'Loan')], max_length=20)),
                ('received_money', models.IntegerField(default=-1)),
                ('give_money', models.IntegerField(default=-1)),
                ('deduct_per_payslip', models.IntegerField()),
                ('desc', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code_name', models.CharField(max_length=10, unique=True)),
                ('found_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCompensations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('compensation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeManagement_app.compensations')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDeductions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('remaining_money', models.IntegerField(default=-1)),
                ('status', models.CharField(default='active', max_length=10)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('deduction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeManagement_app.deductions')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_num', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=200)),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('relegion', models.CharField(choices=[('islam', 'Islam'), ('hindu', 'Hindu'), ('christian', 'Christian'), ('other', 'Other')], max_length=50)),
                ('joined_date', models.DateField()),
                ('photo_url', models.URLField(blank=True, default=None, null=True)),
                ('faculty', models.CharField(max_length=20)),
                ('allowed_leaves', models.SmallIntegerField(default=0)),
                ('main_payscale', models.IntegerField(default=0)),
                ('compensations', models.ManyToManyField(through='employeeManagement_app.EmployeeCompensations', to='employeeManagement_app.compensations')),
                ('deductions', models.ManyToManyField(through='employeeManagement_app.EmployeeDeductions', to='employeeManagement_app.deductions')),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employeeManagement_app.departments')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeManagement_app.employeetype')),
            ],
        ),
        migrations.AddField(
            model_name='employeedeductions',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allDeductions', to='employeeManagement_app.employees'),
        ),
        migrations.AddField(
            model_name='employeecompensations',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allCompensations', to='employeeManagement_app.employees'),
        ),
    ]
