# Generated by Django 5.1.2 on 2024-11-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeManagement_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensations',
            name='money_per_payslip',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='deductions',
            name='deduct_per_payslip',
            field=models.CharField(max_length=20),
        ),
    ]
