# Generated by Django 5.1.2 on 2024-10-18 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeManagement_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deductioneligibility',
            name='employee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibleEmployeeTypeId', to='employeeManagement_app.employeetype'),
        ),
        migrations.AlterField(
            model_name='employeedeductions',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions_details', to='employeeManagement_app.employees'),
        ),
        migrations.CreateModel(
            name='CompensationEligibility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeManagement_app.employeetype')),
            ],
        ),
        migrations.CreateModel(
            name='Compensations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('money_per_payslip', models.IntegerField(default=0)),
                ('eligible_employee_type_id', models.ManyToManyField(through='employeeManagement_app.CompensationEligibility', to='employeeManagement_app.employeetype')),
            ],
        ),
        migrations.AddField(
            model_name='compensationeligibility',
            name='comp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeManagement_app.compensations'),
        ),
        migrations.CreateModel(
            name='EmployeeCompensations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeManagement_app.compensations')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeManagement_app.employees')),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='compensations',
            field=models.ManyToManyField(through='employeeManagement_app.EmployeeCompensations', to='employeeManagement_app.compensations'),
        ),
    ]
