# Generated by Django 5.1.2 on 2024-10-19 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeManagement_app', '0002_alter_deductioneligibility_employee_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deductioneligibility',
            name='deduction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeManagement_app.deductions'),
        ),
        migrations.AlterField(
            model_name='deductioneligibility',
            name='employee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeManagement_app.employeetype'),
        ),
        migrations.AlterField(
            model_name='employeedeductions',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeManagement_app.employees'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeManagement_app.employeetype'),
        ),
    ]
