# Generated by Django 5.1.2 on 2024-10-20 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeManagement_app', '0003_alter_deductioneligibility_deduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecompensations',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allCompensations', to='employeeManagement_app.employees'),
        ),
        migrations.AlterField(
            model_name='employeedeductions',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allDeductions', to='employeeManagement_app.employees'),
        ),
    ]
